name: Deploy CIAP Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Install dependencies
      run: npm install

    - name: Pull latest changes from main
      run: git pull origin main

    - name: Start Angular development server
      run: npm start -- --host=0.0.0.0 --port=8080 --disable-host-check


